### ISSUE TITLE
Getting an error on ULauncher adding extension

### ISSUE THREAD

**Issue by rommmka** [dhelmr/ulauncher-tldr#2]
Message: 'com.github.dhelmr.ulauncher-tldr'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.dhelmr.ulauncher-tldr'

```

**Comment by dhelmr** [comment]
What version of Ulauncher and python are you using?

**Comment by rommmka** [comment]
```
❯ python --version
Python 2.7.18
❯ python3 --version
Python 3.9.7
```
ULauncher 5.10

**Comment by rommmka** [comment]
Just updated to ULauncher 5.1 and it's working now. Thanks.
